repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Secrets Scanner
        entry: trufflehog git file://. --since-commit HEAD --no-verification
        language: system
        pass_filenames: false
        description: Scans the latest commit for secrets using TruffleHog.
        stages: [commit]